name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        env:
          THREATSCOPE_ARTIFACTS: model_artifacts
          THREATSCOPE_DB: test_alerts.db
        run: |
          mkdir -p model_artifacts
          # dummy files so ThreatClassifier won't load during tests
          # tests mock classifier so we don't call real ThreatClassifier in pytest,
          # but create_app __main__ path won't execute anyway. still safe.
          pytest -q
